[package]
name = "cortex-plugin"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
cortex-types = { workspace = true }
cortex-midi = { workspace = true }
rack = "0.4"
crossbeam-channel = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
